### ISSUE TITLE
Terminated due to memory issue

### ISSUE THREAD

**Issue by id-main** [andrewwoz/StreamReader.swift#8] opened 2019-12-16 15:05 UTC
If you call to fast this method, reading let's say another file in seconds. It will leak. Having a file with 300k lines, and iterate like 
var somearray = [String]
 reader.forEach { line in
 somearray.append(line) 
}
try to call the read of different files of 300 k lines in 4 seconds difference.

**Comment by andrewwoz** [comment] 2019-12-17 07:50
Hi @id-main, could you please provide more information about this leak? 
As I understand you are doing the following:
1. Create `LineReader` for first file
2. Create `LineReader` for second file
3. Read one line from first file
4. Read one line from second file
5. Go to step "3".
Is it right?

Note that `LineReader` is not thread safe.

**Comment by andrewwoz** [comment] 2019-12-25 21:09
@id-main Sorry but I can't reproduces this issue. So I'm gonna close it for now. If you will have more detailed steps of how to reproduce it - feel free to reopen it again :)

**Closed as completed by andrewwoz** 2019-12-25 21:09 UTC
Labels: help wanted
